// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: UVCamera

#ifndef _UVCAMERA_UI_H
#define _UVCAMERA_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Image2;
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Button3;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Button4;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_Container2;
extern lv_obj_t * ui_Slider1;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Slider3;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_Button2;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_Button6;
extern lv_obj_t * ui_Label13;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui____initial_actions0;


LV_IMG_DECLARE(ui_img_27510393);    // assets/19e4a089-988b-43ac-befa-1f02090b4762.png



LV_FONT_DECLARE(ui_font_Font14);
LV_FONT_DECLARE(ui_font_Font18);
LV_FONT_DECLARE(ui_font_Font33);



void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
